version: "3.1"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  web1:
    build: ./web01
    ports:
      - "81:5000"

  web2:
    build: ./web02
    ports:
      - "82:5000"

  
  redis:
    image: "redis:alpine"
    ports:
      - "6379"
